src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactory.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactoryDescriptor.java
src/main/java/io/jenkins/plugins/thememanager/none/NoOpThemeManagerFactory.java

Needed to use UnprotectedRootAction so that it works for the login page

Change url generation method

---

docs/developer-guide.md
src/main/java/io/jenkins/plugins/thememanager/Theme.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactory.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactoryDescriptor.java
src/main/java/io/jenkins/plugins/thememanager/none/NoOpThemeManagerFactory.java

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/6

Make APIs as beta

---

README.md
pom.xml
src/main/resources/index.jelly

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/6

Add docs marking as incubated

---

pom.xml
src/main/java/io/jenkins/plugins/thememanager/Theme.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerBluePageDecorator.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java
src/main/resources/io/jenkins/plugins/thememanager/ThemeManagerBluePageDecorator/header.jelly

Part of https://github.com/jenkinsci/dark-theme-plugin/issues/89

Load theme on Blue Ocean

---

src/main/java/io/jenkins/plugins/thememanager/ThemeUserProperty.java

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/14

Add null check for user property retrieval

---

README.md
pom.xml

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/12

Change to incubating

---

src/main/resources/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator/global.jelly

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/13

Reword theme disable

---

src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/21

Fix user preferences loading

---

src/main/java/io/jenkins/plugins/thememanager/none/NoOpThemeManagerFactory.java

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/23

Update no theme name to be "Default"

---

.dependabot/config.yml
.github/dependabot.yml

Saw that this repo was still using the old dependabot config, so I updated it :wink: 
(hope u excuse my slight change in pom formatting, I can remove it if necessary)
* update dependabot config from v1 to v2
* slightly alter pom formatting
* n/a

chore(infra): update dependabot

---

src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactory.java

Fixes #27
@daniel-beck I hope you don't mind me taking this although you are assigned.
Seems like you were just too busy or lost track of it and this bugged me too much...

Use getRootUrlFromRequest

---

Jenkinsfile
pom.xml
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java

Fixes https://github.com/jenkinsci/theme-manager-plugin/issues/81
cc @uhafner

Remove nullness in page decorator

---

docs/creating-a-theme.md
docs/developer-guide.md
docs/theme-properties.md
src/main/java/io/jenkins/plugins/thememanager/Theme.java
src/test/java/io/jenkins/plugins/thememanager/ThemeTest.java

See:
- https://github.com/jenkinsci/theme-manager-plugin/issues/88 
- https://github.com/jenkinsci/prism-api-plugin/pull/41
- https://github.com/jenkinsci/dark-theme-plugin/pull/194
cc @uhafner what do you think of the API?
~(I'll file PRs against dark theme, prism api and design-library as well)~ - complete
Also need to add an extension point to move the UI here but may be a separate PR
and will add docs once it's working end 2 end

Add properties to allow plugins to make suggestions to others

---

src/main/java/io/jenkins/plugins/thememanager/ThemeManagerBluePageDecorator.java

Remove `null` check, `findTheme()` will never return `null`.
-------------------

Remove null checks of non-null values

---

src/main/java/io/jenkins/plugins/thememanager/ThemeUserProperty.java

Depends on https://github.com/jenkinsci/jenkins/pull/7268 but can be released independently
Tested interactively and verified it saves and is gone from the general page

Move theme selection to appearance user page when available

---

src/test/java/io/jenkins/plugins/thememanager/PageDecoratorTest.java
src/test/java/io/jenkins/plugins/thememanager/ThemeManagerJCasCTest.java
src/test/java/io/jenkins/plugins/thememanager/ThemeTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

src/main/resources/io/jenkins/plugins/thememanager/style/main.css
src/main/resources/lib/theme-manager/selector.jelly

Small PR to update the theme preview for the [newly merged header](https://github.com/jenkinsci/jenkins/pull/10245).
**Before**
**After**
@timja want me to bump the minimum Jenkins version or leave as is?
* Works as expected

Update preview for new header

---

README.md

Add Chocolate theme to README.

Add Chocolate theme to README

---

pom.xml
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerFactoryDescriptor.java
src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java
src/main/resources/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator/header.jelly
src/main/resources/io/jenkins/plugins/thememanager/header/main.css
src/main/resources/io/jenkins/plugins/thememanager/header/main.js

https://github.com/user-attachments/assets/e4ac1ae8-5a7c-4c29-8348-797220ae40c9
This PR adds the theme picker to the user account menu, allowing users to switch themes on the fly.
* Menu only shows if the user is signed in, the admin hasn't disabled user picked themes, and the user is not on the appearance page
* Does a POST to store the theme
* Follows the same UI as Pipeline Graph View
* Icon changes depending on theme selected

Add theme picker to account menu

---

docs/creating-a-theme.md

Update documentation to point to theme plugin archetype rather than the empty plugin archetype as it will provide more of a complete plugin upon usage.
N/A

Update documentation to point to theme-plugin archetype

---

docs/creating-a-theme.md

Fix link in 'creating-a-theme.md'
